version: '3'
services:
  psql:
    image: jutonz/k8s-playground-dev-psql:5
    volumes:
      - ./tmp/psql:/var/lib/postgresql/data
  web:
    image: jutonz/k8s-playground-dev-ruby:6
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/root
    ports:
      - '3000:3000'
    depends_on:
      - psql
    links:
      - psql
