version: "2"
services:
  nginx:
    depends_on:
      - rails
      - psql
    image: "jutonz/k8s-playground-prod-nginx:6"
    links:
      - rails
      - psql
    ports:
      - "4444:80"
  psql:
    image: "jutonz/k8s-playground-prod-psql:1"
  rails:
    image: "jutonz/k8s-playground-prod-rails:4"
