apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-ingress
spec:
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: nginx
  externalIPs:
    - 104.131.163.128
