apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: app-port
    port: 443
    targetPort: 443
  - name: http-upgrade-port
    port: 80
    targetPort: 80
  selector:
    app: nginx
  externalIPs:
    - 104.131.163.128
