apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  ports:
  - port: 80
    name: http-upgrade
  - port: 443
    name: https
  selector:
    app: nginx
  externalIPs:
    - 104.131.21.142
