apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
spec:
  tls:
  - hosts:
    - k8s-master.jutonz.com
    secretName: tls-secret
  rules:
  - host: k8s-master.jutonz.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
