apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rails
  name: rails
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rails
    spec:
      containers:
      - image: jutonz/k8s-playground-prod-rails:4
        name: rails
        resources: {}
      restartPolicy: Always
status: {}
